language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker
  - mysql

before_install:
  - docker-compose --file docker-compose-travis.yml up -d

script:
   - mvn clean verify -B

after_success:
  - mvn clean package docker:build -DskipTests=true &&
    docker login -u="$QUAY_USER" -p="$QUAY_PASSWORD" quay.io &&
    docker push quay.io/appdirect/chatty-pie-connector
