apiVersion: v1
kind: Service
metadata:
  labels:
    app: cp-connector
  name: cp-connector
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cp-connector
